version: "3"

networks:
  local:
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak
    restart: always
    command: [start-dev, --import-realm]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    networks:
      - local
    ports:
      - "8080:8080"
      - "8443:8443"
